### ISSUE TITLE
Systemd service script for Datadog agent on CentOS/Fedora

### ISSUE THREAD

**Issue by karnauskas** [DataDog/dd-agent#1216]

**Comment by remh** [comment]
Didn't hear back so i'm closing the issue.

**Comment by jonathanmorley** [comment]
Can this be reopened please

```sudo systemctl enable datadog-agent```

doesn't perform as expected

**Comment by remh** [comment]
@jonathanmorley can you provide a bit more details about it please ?

**Comment by szymonrkainos** [comment]
In Centos 7 init.d files were deprecated ( https://linuxacademy.com/blog/linux/centos-7-take-the-plunge-into-systemd/ ). To manage service correctly (both from linux and automation) perspective we need to have systemd unit provided.
Without it we can't properly automate datadog agent installation, which may generate additional costs (in non-trial licence).

**Comment by remh** [comment]
@szymonrkainos it's something we are planning to do for the next major agent version. It's a few months away though. There are a few ways to work around that in your case though, you can specify dummy api keys that then get replaced, you can check if the agent is running by checking the info page etc..

**Comment by galaxy4public** [comment]
While Datadog works on the next major agent version you can use the following (attached) unit files.  They need to be installed into /etc/systemd/system/ and chmod'ed to 0644.  The units are designed in such a way that the whole agent is controlled by datadog-agent.service.  So you could do stuff like `systemctl start datadog-agent.service`, `systemctl stop datadog-agent.service`, and `systemctl enable datadog-agent.service`.
[datadog-agent-systemd.zip](https://github.com/DataDog/dd-agent/files/714086/datadog-agent-systemd.zip)

**Comment by galaxy4public** [comment]
Additionally, it should be noted that it seems that Datadog never tested their package on a CentOS 7 system since the RPM does not have the required dependencies (e.g. the agent relies on mpstat, which is provided by the sysstat package, yet the datadog-agent package does not require sysstat).  Moreover, if you install the agent on CentOS 7, without my unit files it won't even start since the startup script requires supervisord and it not usually installed on CentOS 7 by default (here, I am actually grad that there is not dependency on supervisord since systemd is superior to it).  Also, there are numerious permission and security issues with the agent, e.g. /opt/datadog-agent and /etc/dd-agent (btw, why a different naming conventions for the directories?) are owned and writable by the dd-agent user (you may want to do `chown -Rh root:dd-agent /opt/datadog-agent /etc/dd-agent && chmod 0750 /opt/datadog-agent /etc/dd-agent` to be much safer.

**Comment by olivielpeau** [comment]
The Datadog agent ships a systemd service file since `5.17.0`, `datadog-agent.service`. Closing this issue.

On an unrelated note: the agent package comes with most of its dependencies built-in (sysstat, supervisor, etc), which is why it doesn't require these deps to be installed system-wide.
