### ISSUE TITLE
wrong url in elastic.py can.connect monitor used for version > 0.90.10

### ISSUE THREAD

**Issue by flutist599** [DataDog/dd-agent#1402]
The new URLS are /_nodes/stats?all=true

But the datadog uses sometimes the old one: /_cluster/nodes/stats?all=true

elastic.py 

*Old* version: (only interesting parts)
/opt/datadog-agent/agent/checks.d/elastic.py

```python
if version >= [0,90,10]:
            if is_external:
                self.STATS_URL = "/_nodes/stats?all=true"
            else:
                self.STATS_URL = "/_nodes/_local/stats?all=true"
else:
            self.STATS_URL = "/_cluster/nodes/stats?all=true"
            self.NODES_URL = "/_cluster/nodes?network=true"```
```

*fixed version* should be: (only interesting parts)
/opt/datadog-agent/agent/checks.d/elastic.py

```python
if version >= [0,90,10]:
            if is_external:
                self.STATS_URL = "/_nodes/stats?all=true"
            else:
                self.STATS_URL = "/_nodes/_local/stats?all=true"
else:
            if is_external:
                self.STATS_URL = "/_nodes/stats?all=true"
            else:
                self.STATS_URL = "/_nodes/_local/stats?all=true"
```

**Comment by remh** [comment]
Thanks a lot for the feedback @flutist599 we will investigate.

**Comment by pbuchner** [comment]
This bug only occurs if there is a problem while getting the metrics.
Per Default the "version" variable is set to [0,0,0] ... and this is smaller then [0,90,10].
But the script should raise an error if it is not possible to get the metrics ... the current version goes ahead and uses therefore the wrong STATS_URL because the version is still at its default value of [0,0,0]
