### ISSUE TITLE
[forwarder] pycurl is required with proxy usage

### ISSUE THREAD

**Issue by wang-arthur** [DataDog/dd-agent#1483]
pycurl is required when the agent is set up with a proxy. Currently, the forwarder logs an error and continues: https://github.com/DataDog/dd-agent/blob/master/ddagent.py#L216-L239, and then the requests with the simplehttp client fail. Instead, the forwarder should fail immediately if proxy settings are configured but pycurl is not installed.

**Comment by yannmh** [comment]
PycURL is actually shipped with the agent. 
https://github.com/DataDog/omnibus-software/blob/master/config/software/tornado.rb
https://github.com/DataDog/omnibus-software/blob/master/config/software/pycurl.rb

Looking at the case, the issue was related to an OpenShift incompatibility with PycURL `7.19.5`. Moving to `7.19.5.1` actually solved the issue.

About your suggestion, I don't think that making the forwarder fail instead of falling back is a good idea. We can discut about it and asses it in the 5.5.0 agent release

**Comment by wang-arthur** [comment]
Thanks @yannmh ! About failing vs. falling back, I think in this case (if I recall correctly), there was a failure either way. The difference would be raising an informative exception if a required package is missing vs. requests failing mysteriously down the line.

**Comment by yannmh** [comment]
The current behavior is the one we expect, i.e. log the error and **try** to fall back with a simple HTTP client. https://github.com/DataDog/dd-agent/blob/master/ddagent.py#L256
Of course we have no guarantee about the fall back attempt and it might fails as well.

I am closing the ticket as we don't have any logs about the failure, but please reo-open if you have more information about it.
