### ISSUE TITLE
Post-install script for Debian package - no error checking for dd-agent users

### ISSUE THREAD

**Issue by sjenriquez** [DataDog/dd-agent#1587]
Submitting on behalf of customer:

Just wanted to submit a bug in the datadog debian package off the datadog apt repository. The post-install script for the debian package doesn't do error checking if the "dd-agent" user already exists. This isn't a huge deal for most people but we like to manage the UID's of our service users. So what we generally do is that we create the user before hand and then install the package. The problem with having to change the UID of the "dd-agent" afterwards is that I then have to change the permissions on all files the "dd-agent" user reads from (which I think is just in /etc/dd-agent and /opt/dd-agent). I'd imagine this isn't a huge priority but I'd imagine other users do the same thing as we do.

**Comment by ng-ops** [comment]
This bug actually breaks the puppet datadog_agent for ubuntu/debian users.  Puppet will try to update to the latest version of datadog-agent package and fail because dd-agent user already exist.  Since part of the installation of the package will tell datadog-agent to stop service first, it causes the agent to stop and not restart itself because the package upgrade fails.

**Comment by remh** [comment]
Thanks for the feedback.
This will be fixed in our 5.5.0 release!
https://github.com/DataDog/dd-agent-omnibus/pull/42/files
