### ISSUE TITLE
Send docker.containers.stopped as 0 when it is 0 instead of skipping key.

### ISSUE THREAD

**Issue by JonGretar** [DataDog/dd-agent#1648]
Currently the dd-agent seems to count stopped containers and send to `docker.containers.stopped`. If there are no stopped containers it seems to skip sending the key at all.

The problem with that arises when I try to monitor the key as in our system there should never be any container that is down for longer than a few seconds for upgrades and such.

However datadog does not seem to count a missing value as 0. So if a container is stopped at 1:00am for 1 minute for upgrade and then another is stopped at 10:00am for a minute then when graphing it in datadog it will show that 1 container has been down continuously for the last 10 hours which is simply not the case.

That means that making a monitor that alerts me when *`docker.containers.stopped` is above or equal '1' on average for the last 10 minutes* will trigger for any stopped container immediately instead of when it has been down for 10 minutes.

**Comment by jsmpereira** [comment]
I have the exact same issue. 

This also means that currently there's no way to "resolve" an alert on this metric. When there are no stopped containers, the fact that there's "No data" does not equal recovering from a threshold.

One might try to use the feature  "automatically resolve this event from a triggered state.". As it states in the Edit Monitor page:

<blockquote>
For some metrics that report periodically across different tags, it may make sense to have triggered alerts auto-resolve after a certain time period. For example, if you have a counter that reports only when an error is fired the alert will never resolve because the metric will never report 0 as the number of errors. In this case, you may want to set your alert to resolve after 4 hours of inactivity on that metric.</blockquote>

But the shortest value of "1 hour" seems a bit too long for something that might be resolved after 5 minutes. And we do want do know as soon as possible if there are no stopped containers.

**Comment by alq666** [comment]
@conorbranagan this is a good use case to investigate on the monitors side.

**Comment by jsmpereira** [comment]
I've noticed what it seems to be another consequence of skipping the `docker.containers.stopped` metric.

It looks like the metric itself is not available until, well its available, which means that we can't create a monitor on this metric until a container actually goes down. It might be possible through the API, but for the web interface some tags, those associated with hosts that have not had containers down yet, are not available when selecting this metric.

**Comment by alq666** [comment]
@jsmpereira there's a way in the monitor editor to specify an arbitrary metric but I agree with you, it's not optimal.

**Comment by JonGretar** [comment]
Yeah I think we should set this as 0. That is the correct metric that show the current state of the system anyway. To have it undefined is simply incorrect metric.

**Comment by remh** [comment]
Fixed in https://github.com/DataDog/dd-agent/pull/1824
