### ISSUE TITLE
[cassandra] add configuration support for Cassandra 2.2+

### ISSUE THREAD

**Issue by jedrzejsieracki** [DataDog/dd-agent#1916]
There are JMX attributes names changes since Cassandra 2.2 and default cassandra.yaml only matches nine of them.

From what I see, the per table WriteCount metrics are gone, so not sure how to proceed with extracting total WriteCount for the cluster - good luck.

**Comment by yannmh** [comment]
Thanks for reporting the issue @jedrzejsieracki !

Starting from Cassandra 2.2+, beans are exposed under the new `org.apache.cassandra.metrics.ColumnFamily` naming convention (rather than the `org.apache.cassandra.db.ColumnFamilies` one). As you highlighted, it means that the beans defined in the default _cassandra.yaml_ file are not matched, thus fetched via JMXFetch.

We are working on fix for Datadog agent 5.6.0, i.e. updating the YAML configuration file and improving JMXFetch 'default' support for these metrics ([more information](https://github.com/DataDog/jmxfetch/issues/6)).

In the meantime, feel free to contact our support team: we;ll be happy to provide you a short term solution with an updated configuration tu monitor your Cassandra 2.2+ instances.

**Comment by jippi** [comment]
I'm hitting the same problem using cassandra 2.2 and almost no data is collected

Can you share an intermediate configuration file that is compatible ?

**Comment by yannmh** [comment]
@jippi would you mind contacting our support team please ? They can provide a short term solution with an updated configuration tu monitor your Cassandra 2.2+ instances.

**Comment by jippi** [comment]
@yannmh been a few months, and still not fixed? :( 

Why not make the configuration public so everyone can benefit and try it out

**Comment by irabinovitch** [comment]
@jippi  Apologies for the delays here.  I will follow up with our team internally to see where we stand on this one.  Feel free to mention me on any PRs or reach out via email anytime.

Regards,
Ilan 
Dir, Technical Community
Datadog

**Comment by gtmtech** [comment]
Hi, whats the status on this? This is holding us up too. thanks!

**Comment by yannmh** [comment]
Hi @gtmtech,

My apologies for the late response. Datadog Agent 5.6.0 changes includes improvements to support Cassandra 2.2+ MBeans. Please see [CHANGELOG](https://github.com/DataDog/dd-agent/blob/master/CHANGELOG.md#changes-3), [#50](https://github.com/DataDog/jmxfetch/pull/50) and [#79](https://github.com/DataDog/jmxfetch/pull/79).

To sum up, the Datadog Agent is now able to pull metrics using the new naming convention and submit them with a **suitable metric name**.

The next step we are working on, is now updating `cassandra.yaml.example` YAML configuration file to actually fetch the new relevant MBeans. Since there is no direct mapping between the 'old' and the 'new' MBeans, we are progressively putting the list together. As an aside, any feedback is also much appreciated :smile:

In the meantime, please feel free to use this temporary YAML file as a workaround.
https://gist.github.com/yannmh/c1a4a85d5cab69be39da

**Comment by olivielpeau** [comment]
The default yaml file has been made compatible with Cassandra 2.2+ by #2142, which will be released with the 5.7.0 agent.

**Comment by olivielpeau** [comment]
Closing this issue as the PR that fixes it (see comment above) is merged into master.
