### ISSUE TITLE
What units does `couchdb.request` time use?

### ISSUE THREAD

**Issue by oliverjanik** [DataDog/dd-agent#1934]
Don't know if this is the right place for support, but I'm having hard time understanding what this metric reports. Is it in miliseconds? Why do both charts differ?

![image](https://cloud.githubusercontent.com/assets/2280140/9984323/a8089d3a-6058-11e5-9616-eef51dcb935e.png)

![image](https://cloud.githubusercontent.com/assets/2280140/9984331/c85980b8-6058-11e5-809a-57fa49c5ce1d.png)

**Comment by yannmh** [comment]
Hello @oliverjanik,

`couchdb.couchdb.request_time` metric is parsed from CouchDB [runtime statistics module](https://wiki.apache.org/couchdb/Runtime_Statistics). Its value is expressed in milliseconds (c.f. http://couchdb-13.readthedocs.org/en/latest/api/misc/).

I reckon both attached charts are likely not making the same query (metric name, scope, aggregation method...). Would you be able to give us more information about it ?

**Comment by remh** [comment]
Closing this issue. @oliverjanik . The reason is that the value exposed by the statistics module is a monotonically increasing counter. If we were to graph it as is, it would just keep increasing. So the dashboard computes the `rate` of this metric computed as per the graphing documentation.
http://docs.datadoghq.com/graphing/
