### ISSUE TITLE
DNS query response monitoring

### ISSUE THREAD

**Issue by eeroniemi** [DataDog/dd-agent#2052]
It would be great to be able to monitor DNS responses. We had issues where we randomly got SERVFAIL status responses from our DNS and as a result this host could not be resolved, and it caused some trouble. 

Would be great to have DNS monitoring bundled to datadog that would do following:

- You can define which host to query for
- You can define which DNS server to use
- Define timeout of the DNS query
- Store response time in milliseconds as gauge metric

This script would create Datadog event if:

- We get timeout
- Hostname is not found
- We get any other status than "NOERROR"

There is DataDog agent check script that someone has created that does almost everything we need, but some features are missing:
- You cannot define DNS server you use
- Response time should be stored in milliseconds (using seconds is not practical because most DNS responses on LAN are on range of 1-30 milliseconds)
- Doesn't validate the status of the response (SERVFAIL or NOERROR etc.) so our errors went unnoticed.

Here is the script for reference:

- dns.py: https://gist.github.com/srkiNZ84/ef5a099bc4787b698fd7
- dns.yaml: https://gist.github.com/srkiNZ84/7bed4a5bd41ac602ad72

**Comment by alq666** [comment]
We should turn this into a service check. This will let us build monitors on top of this check.

**Comment by remh** [comment]
Thanks a lot @eeroniemi . We are scheduling this for our 5.8.0 release

**Comment by hkaj** [comment]
Hi @eeroniemi, I created a new check that should address the requirements you mentioned. It uses a service check instead of events, and the response status is used to set the status of this service check.

It should go out with the next release, in the meantime if you want to give it a try you can add 
https://github.com/DataDog/dd-agent/blob/da7990e46d7568d4ca889f1769a0b414ffecd565/checks.d/dns_check.py
to your `/opt/datadog-agent/agent/checks.d/` folder
and https://github.com/DataDog/dd-agent/blob/da7990e46d7568d4ca889f1769a0b414ffecd565/conf.d/dns_check.yaml.example to `/etc/dd-agent/conf.d/`, tweak the yaml file to your needs and restart the agent.

Let us know what you think :)

**Comment by irabinovitch** [comment]
@eeroniemi I wanted to reach out and let you know that 5.7 is now out and includes this check. We look forward to your thoughts and feedback!

**Comment by CumpsD** [comment]
What do you think about a possibility to define a set of expected IP addresses a DNS entry should resolve to?

We had some cases where somebody accidentally updated a record, which didnt result in a SERVFAIL since there was something listening at the other end. If we had a possibility to monitor if the IP addresses returned from the DNS lookup are still the expected ones, we would have been able to prevent this.
