### ISSUE TITLE
Dogstream fails to monitor log files if they don't exist at startup

### ISSUE THREAD

**Issue by jalaziz** [DataDog/dd-agent#2261]
If a log file is not preset at startup, dogstreams will fail to monitor the file if it ever appears.

The issue appears to be that `self._gen` in `datadog.py` is never unset on an exception. `TailFile.tail()` raises `StopIteration` if the file files to open, but this is thrown on the first call to `self._gen.next()` instead of when `tail()` is called. Future calls to `self._gen.next()` will just raise `StopIteration`.

I'm not sure if this is by design or not. I'm also not sure if unsetting the generator on an exception is always the right thing to do. However, a file that appears (or re-appears -- e.g. after log rotation) after datadog starts seems like a scenario that should be supported.

If this is not by design. I can prepare a pull request.

**Comment by yannmh** [comment]
Thanks lot for the great feedback @jalaziz.

This is not something by design. In fact, the Dogstream project is getting quite old, hasn't been updated for a while, and showing a lot of limits.
For this reason, we are currently in the process of looking for a better replacement for it. We'll keep your feedback in mind and let you informed as we get more updates on this.

Also, we'll be happy to review your pull request if you make one.

**Comment by irabinovitch** [comment]
@jalaziz Thanks for your feedback. Would you be interested in attempting a PR to address this issue?

**Comment by jalaziz** [comment]
@irabinovitch Sure. I'll submit a PR soon.

**Comment by jalaziz** [comment]
Sorry for the delay. I started working on a fix and came up with a pretty simple patch. However, I then realized this can be a bit more complicated than that.

The easy fix is to set the generator to `None` on an exception (we can be more specific and choose to only reset on IO exceptions). However, this doesn't fix the issue of files appearing when using globs. The original glob won't list the missing files, so it won't be in the list of files that we are checking every interval.

I could move the globbing to happen on every check cycle (currently it occurs during in `init`), but not sure if that's worth it. 

So the options seem to be:

1. Only support retrying opens for explicitly listed files (and globbed files that existed at `init` time).
2. Attempt to glob on every check to find new files. This potentially slows the checks down, but makes sure we catch any files that appear dynamically.

Thoughts?

**Comment by gravyboat** [comment]
I also ran into this today with some custom checks. @jalaziz personally I would prefer your first solution as I mostly just want it to 'refresh' and look for the file again instead of not logging any statistics. I'm not sure if the performance impact from 2 would be so bad that it would be a big deal unless a user has tons of dogstreams. Either way I would love to see a PR, as a slower check is still preferable to simply losing data because of a log rotation or service restart where logs are created on startup. Is there any chance you can still propose the PR for this?

**Comment by jalaziz** [comment]
Absolutely. I was just waiting for an opinion on the matter. Will get the PR up for the first option sometime in the next couple of days.

**Comment by gravyboat** [comment]
@jalaziz Thanks I really appreciate it!

**Comment by jalaziz** [comment]
@gravyboat Sorry for the delay. I got caught up with a big push at work. As you can see the fix was really easy. I was just delaying it to try and come up with a better test, but decided I was spending way too much time fighting the tempfile module.

**Comment by gravyboat** [comment]
@jalaziz No worries, thanks for getting this fixed up.

**Comment by nagas** [comment]
https://github.com/DataDog/dd-agent/pull/3480
