### ISSUE TITLE
Mesos intergration references depricated master/slave stats.json endpoint

### ISSUE THREAD

**Issue by DavidXArnold** [DataDog/dd-agent#2365]
As of Mesos 0.23, the stats.json endpoint has been removed and replaced with the /metrics/snapshot endpoint see: https://issues.apache.org/jira/browse/MESOS-2058 . The mesos /mesos_master / mesos_slave integration needs to be updated to use this endpoint.

**Comment by olivielpeau** [comment]
Hi @DavidXArnold,

The `mesos_master` and `mesos_slave` checks already handle this properly by querying the correct endpoint depending on the version of Mesos (see https://github.com/DataDog/dd-agent/blob/5.7.3/checks.d/mesos_master.py#L160-L163 and https://github.com/DataDog/dd-agent/blob/5.7.3/checks.d/mesos_slave.py#L124-L127).

The `mesos` check doesn't handle it but the check is deprecated so we're not going to update it.

I'm going to close this issue since I think it's already solved, but feel free to add a comment here or open a new issue if I've missed anything. Thanks!
