### ISSUE TITLE
get_metadata for EC2 doesn't retrieve availability zone

### ISSUE THREAD

**Issue by matthayes** [DataDog/dd-agent#2415]
The availability zone can be retrieved from `http://169.254.169.254/latest/meta-data/placement/availability-zone`.  Is there any reason not to retrieve it?  Also, if we were to retrieve it, how should it be returned to datadog so it appears in the UI?  I see that when the AWS integration is enabled there is a tag `#availability-zone:blah`.  Does the availability zone need to be added to the list of tags?  I'm looking at `_populate_payload_metadata` specifically and wondering what would need to change.

**Comment by masci** [comment]
Hi @matthayes 
the AWS integration does a great job at reporting those kind of tags, that's why the priority to add such a feature to the agent is extremely low.
If you want to give a shot to it and open a PR it'd be awesome, you can start from [here](https://github.com/DataDog/dd-agent/blob/master/util.py#L420) to see how other metadata are collected.

**Comment by matthayes** [comment]
I found the the `get_metadata` function earlier when I was looking at this.  Getting the availability zone seems easy.  What isn't clear is how it should be returned from the agent.  I traced the metadata to the [payload['meta']](https://github.com/DataDog/dd-agent/blob/0c2afcd1d62ec3f74774ccc055d207b0fbdecaa2/checks/collector.py#L653).  I don't know how the datadog servers will use this metadata.  Ultimately I want it to be a tag that is available for filtering in the UI, like `#availability-zone:us-west-2`, as the AWS integration adds it.  Do I need to update [get_tags](https://github.com/DataDog/dd-agent/blob/eab4b5f40af7002e1740b351d86eae20cf66ae1b/util.py#L363) for this to happen?  By this I mean: update `get_tags` to read from `EC2.metadata` and append the `availability-zone` to `EC2_tags`.

By the way, I tried following the "Setup your environment" instructions earlier and wasn't able to get it working.  Is there a particular version of Ruby I should be using?

Also, there seems to be an inconsistency with security group tags.  [get_tags](https://github.com/DataDog/dd-agent/blob/eab4b5f40af7002e1740b351d86eae20cf66ae1b/util.py#L400) uses `security-group-name:blah` for the tag but it seems the AWS integration uses `security-group:blah`.

**Comment by matthayes** [comment]
By the way, unless I am missing something, the code doesn't seem consistent with the article [How-do-I-pull-my-EC2-tags-without-using-the-AWS-integration](https://help.datadoghq.com/hc/en-us/articles/209922003-How-do-I-pull-my-EC2-tags-without-using-the-AWS-integration-).  The tags mentioned in this article only seem to be returned as metadata.  `EC2.get_tags` [only returns AWS tags and the security group](https://github.com/DataDog/dd-agent/blob/ea028b183544ed7ec2fd902828b2f7ef45bbc746/util.py#L376).  I'm assuming that `EC2.get_tags` is supposed to call `EC2.get_metadata` and add these as tags, just like `GCE.get_tags` does.

**Comment by matthayes** [comment]
@masci can you comment?

**Comment by CharlyF** [comment]
Hi @matthayes,

Thank you for your patience on this issue!
Since we are already discussing this through the Zendesk ticket, I'm going to close this issue so we have a central point of communication.
The product management team is currently reviewing the enhancement of the AWS tag fetching with the agent.
I'll let you know as soon as I hear back.

Best Regards,
Charly

**Comment by matthayes** [comment]
Well, I don't think you should have closed this ticket because it is an unresolved issue and now anyone else interested in this issue can't track the status of it (e.g. ETA for fix).  I could have made the changes with a PR but needed someone to respond.

**Comment by remh** [comment]
@matthayes Thanks for the feedback.

This tag is already collected by the server side AWS integration. It tags your hosts wether you are running the agent or not ? Is it not working in your case ?

**Comment by matthayes** [comment]
I don't want to use the AWS integration because I don't want to be charged by AWS for all the calls from Datadog for EC2.

**Comment by remh** [comment]
@matthayes Thanks for the feedback. 
Unfortunately we are not planning to implement this feature in the short term. 
As previously mentioned, the AWS Integration using the API already collects the availability zone, and with the free tier it should be free in most cases.

So i'm close this issue but i won't lock the conversation so we can reopen if it gets more traction. 
Thanks again for the feedback.

**Comment by matthayes** [comment]
I was willing to implement the feature myself.  Oh well.

**Comment by martinb3** [comment]
Hi there -- I'm also in a situation where I have thousands of AWS accounts I don't want to configure for the AWS integration, but just want EC2 tags. It'd be great if the agent could collect/send them, since they're already available to the agent and custom tags are already being collected from the IMDS-related calls.
