### ISSUE TITLE
[feature] Hashicorp's Nomad scheduler support

### ISSUE THREAD

**Issue by jippi** [DataDog/dd-agent#2959]
Today Hashicorp's Nomad scheduler ( https://www.nomadproject.io/ / https://github.com/hashicorp/nomad ) got basic statsd support, but this is far from ideal when it comes to aggregating and working with the data within datadog.

Having a datadog telemetry output in Nomad directly, or a dd-agent check that can scrape out the information from the Nomad client HTTP API ( https://www.nomadproject.io/docs/http/index.html ) would be very nice!

**Comment by irabinovitch** [comment]
@jippi  We've been looking into this with the HashiCorp folks. The main issue at the moment is that the metric names emitted by Nomad to dogstatsd contain per container and per hostname ids in them, rather than setting those as tags.  Once this is fixed in Nomad or GoMetrics we'll have some killer dashboards to show you.

**Comment by jippi** [comment]
@irabinovitch nice! :)

**Comment by jippi** [comment]
this is actually done
