### ISSUE TITLE
error on navigation before load

### ISSUE THREAD

**Issue by shanimal** [DataDog/dd-agent#3465]
Im working on a site that uses dd-agent iframes on an admin panel. If I go to the panel then immediately navigate away I get the following errors in the console.

![_devprt-1609__possible_timing_issues_will_occur_if_user_quickly_clicks_on_another_tab_after_logging_in_as_super_user_-_machine_zone_jira](https://user-images.githubusercontent.com/283957/28894893-25ab52dc-778b-11e7-8b8d-285f6d0693a5.jpg)

To work around the issue temporarily I did a dns-prefetch.
`<link rel="dns-prefetch" href="//app.datadoghq.com">`

**Comment by xvello** [comment]
Hi @shanimal 

This repository is holding the `dd-agent` source and its related issues. As this issue is related to our frontend system, you should report it to [our support team](https://www.datadoghq.com/support/) that will help you work around it, and escalate to the appropriate team if needed.

Regards

**Comment by shanimal** [comment]
Thank you. I submitted the details. 

I would love to do a pull request to fix the issue. If I knew where to do that.
