### ISSUE TITLE
Incorrect k8s namespace detection

### ISSUE THREAD

**Issue by mausch** [DataDog/dd-agent#3588]
Running `datadog/docker-dd-agent:12.4.5181` on Kubernetes v1.5.7, I'm getting loads of errors like this:

```
ERROR | dd.collector | collector(leader_elector.py:122) | Failed to get config map datadog-leader-elector. Error: 500 Server Error: Internal Server Error for url: https://10.0.0.1:443/api/v1/namespaces/default/configmaps/datadog-leader-elector
```

Not sure why it's a 500, but the issue here is that dd-agent seems to [detect that its namespace](https://github.com/DataDog/dd-agent/blob/master/utils/kubernetes/leader_elector.py#L115) is `default` when it's actually running in `kube-system`

**Comment by hkaj** [comment]
Hey @mausch, thanks for reaching out. 
Do you see this log line in `/var/log/datadog/collector.log`? https://github.com/DataDog/dd-agent/blob/2ba241ed2e5fb89fa872ee3cb029a1177dd89917/utils/kubernetes/kubeutil.py#L281

This may be due to pod_name override, meaning this condition doesn't match : https://github.com/DataDog/dd-agent/blob/2ba241ed2e5fb89fa872ee3cb029a1177dd89917/utils/kubernetes/kubeutil.py#L279

If you're having trouble finding the log files, feel free to [send our support team a flare](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command)

**Comment by mausch** [comment]
Ah, indeed I'm getting that warning.
However the `KUBERNETES_POD_NAME` env var is not set, `HOSTNAME` is not set either and DD_HOSTNAME is set to the pod name i.e.:

```
- name: DD_HOSTNAME
   valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

**Comment by hkaj** [comment]
@mausch mind pasting here (or in a gist) the yaml you use to deploy the agent (minus the api key)?

**Comment by mausch** [comment]
Here's the daemonset manifest, I just copied it from the dashboard: https://gist.github.com/mausch/ef0d9f1b37b733bdb06a9346713e9b66

**Comment by hkaj** [comment]
That's likely due to `hostNetwork: true`. The agent tries and find his namespace by finding its pod name in the kubelet pod list, and extract the associated namespace. But the value it takes for pod name is set here: https://github.com/DataDog/dd-agent/blob/2ba241ed2e5fb89fa872ee3cb029a1177dd89917/utils/kubernetes/kubeutil.py#L109-L110 and `$HOSTNAME` is set to the node name if you're in host networking mode.

Could you use the downward api to pass it the pod name in the `KUBERNETES_POD_NAME` environment var? That should fix the issue. BTW you can just replace `DD_HOSTNAME` by `KUBERNETES_POD_NAME` in the manifest, I don't think dd_hostname is used by anything anymore.

**Comment by mausch** [comment]
I'm now deploying Datadog via a Helm chart and I'm no longer seeing this error.
