### ISSUE TITLE
arm64 package builds

### ISSUE THREAD

**Issue by optix2000** [DataDog/dd-agent#3621]
Looks like there exists `armhf` (RasPi) builds of the agent in dd apt repo, but not `arm64`, which is much more common among actual ARM servers (eg Cavium ThunderX). Would it be possible to also add builds and packages for `arm64`?

**Comment by masci** [comment]
Hi @optix2000 thanks for reaching out.

Our repo might use a little clean up, we don't actually support any build targeting ARM and this will likely stay like this since we're focusing our efforts on the [new Agent](https://github.com/DataDog/datadog-agent/).

The new Agent comes in different flavors, one of those is what we call "puppy", a lightweight version capable to crosscompile to ARM. The Puppy Agent will be officially supported and we also have some work in the backlog to build and distribute the full fledged version on ARM.
