### ISSUE TITLE
python-dateutil missing in 5.24.0

### ISSUE THREAD

**Issue by manos** [DataDog/dd-agent#3745]
I expected dateutil to go missing in 6.x, but we just upgraded 5.20.* to 5.24.0, and python-dateutil is no longer bundled. Is this an error, or do I have to account for that going forward in the 5.x train?

Thanks!

**Comment by olivielpeau** [comment]
Hi @manos, I think `python-dateutil` was shipped only because it was a sub-dependency of a python module we shipped in 5.20.x, and that we must have upgraded or removed since. In any case you can assume the Agent 5 package will not ship this module going forward.

I'll go ahead and close this issue, but feel free to respond here if you have any questions, thanks!

**Comment by manos** [comment]
Ah, so it was just luck that my custom checks could import datetime modules :)
Cool; thanks for explaining!
