### ISSUE TITLE
Have a ping check.d

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#599]
It is sometimes desirable to have metrics on ping times between a node with an agent and a target host.
Similar to [check_ping](http://nagiosplugins.org/man/check_ping) - but collecting the metrics involved. Might be as simple as [this](https://github.com/scoutapp/scout-plugins/blob/master/ping/ping.rb) with some more metrics.
Derive some ideas from [here](https://github.com/jedie/python-ping/blob/master/ping.py) as well.

**Comment by laslowh** [comment]
Is there any update on this.  FWIW, you could use "setcap" with the "cap_net_raw" capability on linux.  Probably no less dicey to deploy though.

**Comment by nambrosch** [comment]
a while ago i created a ping integration (which works fine on linux and freebsd) but needed more polishing to ship with the dd agent.  i never finished it and probably won't.. here's the pr:

https://github.com/DataDog/dd-agent/pull/1116

since a regular datadog check is run in a single thread there ends up being a cap on the number of hosts you can ping before running out of time, which really limits the usefulness of the check, so i came up with this instead:

https://gist.github.com/nambrosch/13679710eca4a268f775

i run it in screen and use python multiprocessing to ping hosts asynchronously and return the data via dogstatsd.  not perfect but it works for me and there's no cap on the number of destinations.

**Comment by olivielpeau** [comment]
The `5.7.0` version of the Agent on Linux will bundle [`go-metro`](https://github.com/DataDog/go-metro), a new component that measures TCP RTT.

Closing this issue, feel free to give feedback on `go-metro` by opening a new issue.
