### ISSUE TITLE
Counter normalization for dogstatsd does not make sense

### ISSUE THREAD

**Issue by camerondavison** [DataDog/dd-agent#659]
I spent some time trying to figure out which part of the system is breaking down, but I am not really sure.

Currently if you send "increment(metric)" to dogstatsdb it gets normalized by an interval. So in the default setup the interval is 10 seconds and so therefore before sending the metric to data dog it is normalized by dividing by 10.

This means that if you have one event happen then it is sending the value .1 to datadog for that 10 second interval. Then when you are create a graph in datadog such as "q":"sum(metricname)"
will show a sum of ".1" for that time period, rather than what you should expect which is 1.

Also if you had an event every second you would see 1 as instead of 10 like you would expect.

Why was normalization ever implemented in #254 , does it have to do with the webapp? Shouldn't we be sending the value of the counter rather than the normalization of the counter?

The quote "At present, if a dogstream plugin sends 4 counters, with value 1, at distinct seconds within the same minute, this case (4 counter events) is visually indistinguishable from the situation in which only a single counter datapoint, likewise with value 1, is sent." Would this show up as 4 and not 1? How are these visually indistinguishable? I guess the problem could come with "avg:(metricname)" in the webapp, but I would assume that you would want the webapp to do the normalization with the avg function instead.

**Comment by vishalsurana** [comment]
How do you deal with data that hasn't yet arrived, but will eventually? For instance, if a sum is defined on a metric that's produced by 3 hosts and only one host has emitted a value. Then do you extrapolate the values for other hosts (until the data arrives)? If you do extrapolate, then do you go back in time and adjust the value of the sum as and when data points belonging to the same window arrive? How long do you wait for data points to arrive before you output a value for a window? I'm asking this because we have defined monitors on some spatially aggregated metrics and they sometimes trigger false alerts. I'm not sure whether its because of extrapolation or whether its because the aggregation is performed on a limited dataset. With plotting I've noticed that the value of the last data (aggregated) point is sometimes inaccurate, but after data from other agents comes, then the graph is updated to reflect the true value. But with monitors, its not clear how you can "go back in time" since you may have already sent an alert message (to other applications).
