### ISSUE TITLE
DD user agent does not have access to I/O counters for process 

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#866]
I get this error from dd-agent on Ubuntu LTS and I wasn't able to find any hints regarding what I need to do to solve it.

**Comment by mohitkhanna** [comment]
+1 Just had a chat with support and they pointed me to this thread. Just a day back one of our services had a bug wherein a huge amount of /dev/null fds were being leaked and it eventually crashed raising an alert for process down.

While reproducing the issue we used `sudo lsof | wc -l` in a loop to see the pattern and it should a consistent increase.

None of the default system level metrics collected by dd-agent indicated this growth. Had this metric been there we would have known way earlier about this issue (takes a day to crash the service).

Support mentioned that this may coming in later agent version - I just wanted to put our live crash scenario here to indicate that adding this soon will really help a lot. For now we have written our own customer scripts to periodically send across this metric to DataDog for plotting.

A very basic metric is missing.

**Comment by grayaii** [comment]
I know this issue is Closed, but it seems to me it was "closed" due to "not implementing", but I think DataDog has indeed fixed this issue:
These metrics: https://docs.datadoghq.com/integrations/system/ contain:
system.fs.file_handles.used, which is the equivalent of:
cat /proc/sys/fs/file-nr
And
system.fs.file_handles.max is the equivalent of:
cat /proc/sys/fs/file-max

Therefore, you can easily create a percentage in your alarm.

These metrics are the global/system open file descriptors.  The difference between lsof and /proc/sys/fs/file-nr is here, but basically, you want "cat /proc/sys/fs/file-nr", not lsof, which is what datadog is collecting:
https://unix.stackexchange.com/questions/176967/why-file-nr-and-lsof-count-on-open-files-differs
