### ISSUE TITLE
W: GPG error: http://apt.datadoghq.com unstable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 226AE980C7A7DA52

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#934]
`W: GPG error: http://apt.datadoghq.com unstable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 226AE980C7A7DA52`

**Comment by Zaelot** [comment]
Encountered similar error with Azure's Datadog Extension (on Ubuntu 18.04):
```
W: GPG error: http://apt.datadoghq.com stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4B4593018387EEAF
E: The repository 'http://apt.datadoghq.com stable Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```
..I assume it's not this old version of the agent, but just reporting here.

Fixed by adding the new key from here: [https://help.datadoghq.com/hc/en-us/articles/360000886852-Agent-APT-Repo-Key-Rotation](https://help.datadoghq.com/hc/en-us/articles/360000886852-Agent-APT-Repo-Key-Rotation)
and installing again:
https://app.datadoghq.com/account/settings#agent/ubuntu
