### ISSUE TITLE
[core] processes run in foreground do not have PID files

### ISSUE THREAD

**Issue by celenechang** [DataDog/dd-agent#941]
collector status command seems to return an incorrect message. reported from a user, also tested locally:

$ dd-agent status
Log file is unwritable: '/var/log/datadog/collector.log'
2014-05-13 16:38:36,284 | DEBUG | dd.collector | config(config.py:523) | No proxy configured
2014-05-13 16:38:36,284 | DEBUG | dd.collector | util(util.py:387) | Using temporary pid file: /tmp/dd-agent.pid
2014-05-13 16:38:36,284 | INFO | dd.collector | daemon(daemon.py:250) | Agent is not running
Agent is not running

$ sudo supervisorctl -c /etc/dd-agent/supervisor.conf status
datadog-agent:collector          RUNNING    pid 6279, uptime 3 days, 21:34:41
datadog-agent:dogstatsd          RUNNING    pid 6277, uptime 3 days, 21:34:41
datadog-agent:forwarder          RUNNING    pid 6278, uptime 3 days, 21:34:41
datadog-agent:pup                RUNNING    pid 6280, uptime 3 days, 21:34:41

**Comment by LeoCavaille** [comment]
This is caused by how we run these daemons through supervisor.
We ask supervisor to launch the collector or dogstatsd in foreground mode therefore bypassing the `daemonizing` methods that handle pid files.
As a consequence there are no pid files when running the agent with supervisor (and `status` will return not running), should you use `dd-agent start` instead it would return the appropriate status.

The solution would be to handle the pidfile directly in `run()` or use the same `start` interface of the daemon adding an extra flag `foreground` for instance.
